name: CI - Validation

permissions:
  contents: read

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: x86_64_tahoe
    if: github.repository_owner == 'dortania'
    steps:
      - uses: actions/checkout@v6
      - name: Validate
        run: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3 OpenCore-Patcher-GUI.command --validate
